#[layers.spring]
#  modules = [
#        "org.springframework.boot:spring-boot-starter-web:jar:2.3.4.RELEASE",
#        "org.springframework.boot:spring-boot-starter:jar:2.3.4.RELEASE",
#        "org.springframework.boot:spring-boot:jar:2.3.4.RELEASE",
#        "org.springframework.boot:spring-boot-autoconfigure:jar:2.3.4.RELEASE",
#        "org.springframework.boot:spring-boot-starter-logging:jar:2.3.4.RELEASE",
#        "ch.qos.logback:logback-classic:jar:1.2.3",
#        "ch.qos.logback:logback-core:jar:1.2.3",
#        "org.apache.logging.log4j:log4j-to-slf4j:jar:2.13.3",
#        "org.apache.logging.log4j:log4j-api:jar:2.13.3",
#        "org.slf4j:jul-to-slf4j:jar:1.7.30",
#        "jakarta.annotation:jakarta.annotation-api:jar:1.3.5",
#        "org.yaml:snakeyaml:jar:1.26",
#        "org.springframework.boot:spring-boot-starter-json:jar:2.3.4.RELEASE",
#        "com.fasterxml.jackson.core:jackson-databind:jar:2.11.2",
#        "com.fasterxml.jackson.core:jackson-annotations:jar:2.11.2",
#        "com.fasterxml.jackson.core:jackson-core:jar:2.11.2",
#        "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.11.2",
#        "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.2",
#        "com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.11.2",
#        "org.springframework:spring-web:jar:5.2.9.RELEASE",
#        "org.springframework:spring-beans:jar:5.2.9.RELEASE",
#        "org.springframework:spring-webmvc:jar:5.2.9.RELEASE",
#        "org.springframework:spring-aop:jar:5.2.9.RELEASE",
#        "org.springframework:spring-context:jar:5.2.9.RELEASE",
#        "org.springframework:spring-expression:jar:5.2.9.RELEASE",
#        "org.springframework.boot:spring-boot-starter-jetty:jar:2.3.4.RELEASE",
#        "jakarta.servlet:jakarta.servlet-api:jar:4.0.4",
#        "jakarta.websocket:jakarta.websocket-api:jar:1.1.2",
#        "org.eclipse.jetty:jetty-servlets:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-continuation:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-http:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-util:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-io:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-webapp:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-xml:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-servlet:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-security:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-server:jar:9.4.31.v20200723",
#        "org.eclipse.jetty.websocket:websocket-server:jar:9.4.31.v20200723",
#        "org.eclipse.jetty.websocket:websocket-common:jar:9.4.31.v20200723",
#        "org.eclipse.jetty.websocket:websocket-api:jar:9.4.31.v20200723",
#        "org.eclipse.jetty.websocket:websocket-client:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-client:jar:9.4.31.v20200723",
#        "org.eclipse.jetty.websocket:websocket-servlet:jar:9.4.31.v20200723",
#        "org.eclipse.jetty.websocket:javax-websocket-server-impl:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-annotations:jar:9.4.31.v20200723",
#        "org.eclipse.jetty:jetty-plus:jar:9.4.31.v20200723",
#        "org.ow2.asm:asm:jar:7.3.1",
#        "org.ow2.asm:asm-commons:jar:7.3.1",
#        "org.ow2.asm:asm-tree:jar:7.3.1",
#        "org.ow2.asm:asm-analysis:jar:7.3.1",
#        "org.eclipse.jetty.websocket:javax-websocket-client-impl:jar:9.4.31.v20200723",
#        "org.glassfish:jakarta.el:jar:3.0.3",
#        "org.slf4j:slf4j-api:jar:1.7.30",
#        "org.springframework:spring-core:jar:5.2.9.RELEASE",
#        "org.springframework:spring-jcl:jar:5.2.9.RELEASE",
#  ]

[layers.core]
# need to declare transitive spring dependencies here, since they are not found if parent=spring layer is used
  modules = [
    "org.springframework.boot:spring-boot-starter-web:jar:2.3.4.RELEASE",
    "org.springframework.boot:spring-boot-starter:jar:2.3.4.RELEASE",
    "org.springframework.boot:spring-boot:jar:2.3.4.RELEASE",
    "org.springframework.boot:spring-boot-autoconfigure:jar:2.3.4.RELEASE",
    "org.springframework.boot:spring-boot-starter-logging:jar:2.3.4.RELEASE",
    "ch.qos.logback:logback-classic:jar:1.2.3",
    "ch.qos.logback:logback-core:jar:1.2.3",
    "org.apache.logging.log4j:log4j-to-slf4j:jar:2.13.3",
    "org.apache.logging.log4j:log4j-api:jar:2.13.3",
    "org.slf4j:jul-to-slf4j:jar:1.7.30",
    "jakarta.annotation:jakarta.annotation-api:jar:1.3.5",
    "org.yaml:snakeyaml:jar:1.26",
    "org.springframework.boot:spring-boot-starter-json:jar:2.3.4.RELEASE",
    "com.fasterxml.jackson.core:jackson-databind:jar:2.11.2",
    "com.fasterxml.jackson.core:jackson-annotations:jar:2.11.2",
    "com.fasterxml.jackson.core:jackson-core:jar:2.11.2",
    "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.11.2",
    "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.2",
    "com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.11.2",
    "org.springframework:spring-web:jar:5.2.9.RELEASE",
    "org.springframework:spring-beans:jar:5.2.9.RELEASE",
    "org.springframework:spring-webmvc:jar:5.2.9.RELEASE",
    "org.springframework:spring-aop:jar:5.2.9.RELEASE",
    "org.springframework:spring-context:jar:5.2.9.RELEASE",
    "org.springframework:spring-expression:jar:5.2.9.RELEASE",
    "org.springframework.boot:spring-boot-starter-jetty:jar:2.3.4.RELEASE",
    "jakarta.servlet:jakarta.servlet-api:jar:4.0.4",
    "jakarta.websocket:jakarta.websocket-api:jar:1.1.2",
    "org.eclipse.jetty:jetty-servlets:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-continuation:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-http:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-util:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-io:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-webapp:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-xml:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-servlet:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-security:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-server:jar:9.4.31.v20200723",
    "org.eclipse.jetty.websocket:websocket-server:jar:9.4.31.v20200723",
    "org.eclipse.jetty.websocket:websocket-common:jar:9.4.31.v20200723",
    "org.eclipse.jetty.websocket:websocket-api:jar:9.4.31.v20200723",
    "org.eclipse.jetty.websocket:websocket-client:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-client:jar:9.4.31.v20200723",
    "org.eclipse.jetty.websocket:websocket-servlet:jar:9.4.31.v20200723",
    "org.eclipse.jetty.websocket:javax-websocket-server-impl:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-annotations:jar:9.4.31.v20200723",
    "org.eclipse.jetty:jetty-plus:jar:9.4.31.v20200723",
    "org.ow2.asm:asm:jar:7.3.1",
    "org.ow2.asm:asm-commons:jar:7.3.1",
    "org.ow2.asm:asm-tree:jar:7.3.1",
    "org.ow2.asm:asm-analysis:jar:7.3.1",
    "org.eclipse.jetty.websocket:javax-websocket-client-impl:jar:9.4.31.v20200723",
    "org.glassfish:jakarta.el:jar:3.0.3",
    "org.slf4j:slf4j-api:jar:1.7.30",
    "org.springframework:spring-core:jar:5.2.9.RELEASE",
    "org.springframework:spring-jcl:jar:5.2.9.RELEASE",

# TODO find out how to use parent first classloading strategy...

    "com.github.thomasdarimont.layrry.demo:spring-boot-layrry-app:{{spring_boot_layrry_demo_version}}",
    "com.github.thomasdarimont.layrry.demo:spring-boot-layrry-core:{{spring_boot_layrry_demo_version}}",
    "org.moditect.layrry:layrry-platform:{{layrry_version}}"]

#  parents = ["spring"]

#[layers.plugins]
#  parents = ["core"]
#  directory = "plugins"

[main]
  module = "com.github.thomasdarimont.layrry.demo.app"
  class = "com.github.thomasdarimont.layrry.demo.app.App"